# Generated by Django 3.2.5 on 2021-11-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housename', models.CharField(default='Nothing to fill in about the house.', max_length=50, verbose_name='house name')),
                ('community', models.CharField(default='Nothing to fill in about the house.', max_length=200, verbose_name='community')),
                ('describe', models.CharField(default='Nothing to fill in about the house.', max_length=500, verbose_name='describe')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='price')),
                ('housearea', models.CharField(default='Nothing to fill in about the house.', max_length=50, verbose_name='housearea')),
                ('address', models.CharField(default='Nothing to fill in about the house.', max_length=50, verbose_name='address')),
                ('floor', models.CharField(default='Nothing to fill in about the house.', max_length=50, verbose_name='floor')),
                ('building_age', models.CharField(default='Nothing to fill in about the house.', max_length=5, verbose_name='building_age')),
                ('house_type', models.CharField(default='Nothing to fill in about the house.', max_length=5, verbose_name='house_type')),
                ('surrounding_facilities', models.CharField(default='Nothing to fill in about the house.', max_length=500, verbose_name='surrounding_facilities')),
                ('is_delete', models.BooleanField(default=False, verbose_name='if deleted')),
                ('shelf_status', models.BooleanField(default=True, verbose_name='shelf_status')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.CharField(default='Nothing to fill in about the house.', max_length=200, verbose_name='community')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=32, verbose_name='password')),
                ('telephone', models.IntegerField(default='13100000000', verbose_name='telephone')),
                ('is_delete', models.BooleanField(default=False, verbose_name='if deleted')),
                ('is_valid', models.BooleanField(default=True, verbose_name='if valid')),
                ('role_type', models.IntegerField(default=1, verbose_name='role type')),
                ('user_level', models.IntegerField(default=1, verbose_name='user level')),
                ('head_portrait', models.ImageField(blank=True, upload_to='', verbose_name='head portrait')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
            ],
        ),
    ]
