# Generated by Django 3.2.5 on 2021-11-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introducer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='head_portrait',
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(default='Where is the house.', max_length=50, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='house',
            name='building_age',
            field=models.CharField(default='The age of the house.', max_length=5, verbose_name='building_age'),
        ),
        migrations.AlterField(
            model_name='house',
            name='community',
            field=models.CharField(default='The community where the house is located.', max_length=200, verbose_name='community'),
        ),
        migrations.AlterField(
            model_name='house',
            name='describe',
            field=models.CharField(default='Describe about the house.', max_length=500, verbose_name='describe'),
        ),
        migrations.AlterField(
            model_name='house',
            name='floor',
            field=models.CharField(default='How many floors is the house on.', max_length=50, verbose_name='floor'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(default='The type of house.', max_length=5, verbose_name='house_type'),
        ),
        migrations.AlterField(
            model_name='house',
            name='housearea',
            field=models.CharField(default='The size of the house.', max_length=50, verbose_name='housearea'),
        ),
        migrations.AlterField(
            model_name='house',
            name='housename',
            field=models.CharField(default='House name.', max_length=50, verbose_name='house name'),
        ),
        migrations.AlterField(
            model_name='house',
            name='surrounding_facilities',
            field=models.CharField(default='Facilities around the house.', max_length=500, verbose_name='surrounding_facilities'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.IntegerField(default='0000', verbose_name='telephone'),
        ),
    ]
