# Generated by Django 3.2.5 on 2021-11-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introducer', '0002_auto_20211108_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.CharField(default='This is my personal signature in a word!', max_length=200, verbose_name='personal signature'),
        ),
    ]
