# Generated by Django 3.2.5 on 2021-11-11 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('introducer', '0003_user_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='foreigtousersubscriber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='introducer.user'),
        ),
    ]
