# Generated by Django 3.2.5 on 2021-11-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introducer', '0004_house_foreigtousersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='media/introducer/profile', upload_to='media/introducer/profile'),
        ),
    ]
