# Generated by Django 3.2.5 on 2021-11-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introducer', '0005_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='media/introducer/profile', upload_to='media/introducer/profile')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
