# Generated by Django 3.2.5 on 2021-11-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introducer', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
