# Generated by Django 3.2.5 on 2021-11-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introducer', '0008_remove_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='introducer/profile', upload_to='introducer/profile'),
        ),
    ]
