# Generated by Django 3.2.5 on 2021-11-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introducer', '0013_remove_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='media/introducer/profile/', upload_to='media/introducer/profile/default1.jpg'),
        ),
    ]
