# Generated by Django 3.2.5 on 2021-12-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introducer', '0015_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='air_conditioner',
            field=models.BooleanField(default=False, verbose_name='air_conditioner'),
        ),
        migrations.AddField(
            model_name='house',
            name='deposit',
            field=models.BooleanField(default=False, verbose_name='deposit'),
        ),
        migrations.AddField(
            model_name='house',
            name='heater',
            field=models.BooleanField(default=False, verbose_name='heater'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_origin_type',
            field=models.CharField(choices=[('di', 'direct'), ('tr', 'transfer'), ('me', 'mediator'), ('ot', 'others')], default='', max_length=20, verbose_name='rent type'),
        ),
        migrations.AddField(
            model_name='house',
            name='housevideo',
            field=models.ImageField(default='media/introducer/housevideos/', upload_to='media/introducer/housevideos/'),
        ),
        migrations.AddField(
            model_name='house',
            name='kitchen_room',
            field=models.BooleanField(default=False, verbose_name='kitchen_room'),
        ),
        migrations.AddField(
            model_name='house',
            name='lift',
            field=models.BooleanField(default=False, verbose_name='lift'),
        ),
        migrations.AddField(
            model_name='house',
            name='refrigerator',
            field=models.BooleanField(default=False, verbose_name='refrigerator'),
        ),
        migrations.AddField(
            model_name='house',
            name='rent_type',
            field=models.CharField(choices=[('sh', 'share'), ('fu', 'full')], default='', max_length=20, verbose_name='rent type'),
        ),
        migrations.AddField(
            model_name='house',
            name='subway',
            field=models.BooleanField(default=False, verbose_name='subway'),
        ),
        migrations.AddField(
            model_name='house',
            name='washer',
            field=models.BooleanField(default=False, verbose_name='washer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='media/introducer/profile/default.jpg', upload_to='media/introducer/profile/'),
        ),
    ]
