# Generated by Django 3.2.5 on 2021-12-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introducer', '0016_auto_20211208_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.CharField(default=1, max_length=10, verbose_name='house id')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='order amount')),
                ('subscriber_id', models.CharField(default=1, max_length=10, verbose_name='subscriber id')),
                ('publisher_id', models.CharField(default=2, max_length=15, verbose_name='publisher id')),
                ('publisher_name', models.CharField(default='publisher name', max_length=30, verbose_name='publisher name')),
                ('orderStatus', models.CharField(default='0', max_length=10, verbose_name='orderStatus')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
            ],
        ),
    ]
